import streamlit as st
import pandas as pd
import geopandas as gpd
import folium
from streamlit_folium import st_folium

st.set_page_config(page_title="Citi Bike Coverage Gaps", layout="wide")

st.title("🚲 Lower Manhattan Citi Bike Accessibility")
st.markdown("Identifying underserved blocks based on station proximity.")

# Load your processed GeoJSON (output from your pipeline)
@st.cache_data
def load_data():
    # This file would be generated by your pipeline.py
    gdf = gpd.read_file("data/processed_accessibility.geojson")
    return gdf

data = load_data()

# Sidebar filters
neighborhood = st.sidebar.multiselect("Filter by Neighborhood", options=data['NTA'].unique())

# Map Logic
m = folium.Map(location=[40.7128, -74.0060], zoom_start=13, tiles="cartodbpositron")

# Add Choropleth
folium.Choropleth(
    geo_data=data,
    name="Accessibility",
    data=data,
    columns=["block_id", "dist_to_nearest"],
    key_on="feature.properties.block_id",
    fill_color="YlOrRd",
    legend_name="Distance to Nearest Station (meters)"
).add_to(m)

st_folium(m, width=1000)